trigger:
- Master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)01-currency-exchange-microservice-basic/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key = $(publickey.secureFilePath)'
    backendAzureRmUseEnvironmentVariablesForAuthentication: false
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'azure-devops-service-connection'
    backendAzureRmResourceGroupName: 'techtutorialwithram_group'
    backendAzureRmStorageAccountName: 'ramkubernetesxyz'
    backendAzureRmContainerName: 'ram_kubernetes'
    backendAzureRmKey: 'ram_k8s'