trigger:
- Master

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
variables:
  Enviroment: Dev 
  jobs:
  - job: job1
    steps:
    - script: echo $(Enviroment)Hello, world!
      displayName: 'Run a one-line script'
  - job: job2
    steps:
      - script: |
          echo Hello, world!
          echo Ram Parkash
        displayName: 'Run a one-line script'