trigger:
- Master

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: job1
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
  - job: job2
    steps:
      - script: |
          echo Hello, world!
          echo Ram Parkash
        displayName: 'Run a one-line script'
- stage: Dev
  jobs:
  - job: job1
    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
  - job: job2
    steps:
      - script: |
          echo Hello, world!
          echo Ram Parkash
        displayName: 'Run a one-line script'
- stage: QA
  jobs:
  - job: job1
    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
  - job: job2
    steps:
      - script: |
          echo Hello, world!
          echo Ram Parkash
        displayName: 'Run a one-line script'
- stage: Prod
  jobs:
  - job: job1
    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
  - job: job2
    steps:
      - script: |
          echo Hello, world!
          echo Ram Parkash
        displayName: 'Run a one-line script'