trigger:
- Master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformCLI@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendAzureRmUseEnvironmentVariablesForAuthentication: true
    backendAzureRmUseEntraIdForAuthentication: true
    backendServiceArm: 'azure'
    backendAzureRmResourceGroupName: 'techtutorialwithram_group'
    backendAzureRmStorageAccountName: 'azueaccvms'
    backendAzureRmContainerName: 'ramk8s'
    backendAzureRmKey: 'ram_kubernetes'
