trigger:
- Master

pool:
  vmImage: ubuntu-latest
jobs:
- job: job1
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
    
- job: job2
  dependsOn:
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
- job: job3
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'


