trigger:
- Master

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: job1
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
- stage: Dev
  jobs:
  - job: job1
    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'