trigger:
- Master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/01-currency-exchange-microservice-basic/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-devops-service-connection'
    backendAzureRmResourceGroupName: 'techtutorialwithram_group'
    backendAzureRmStorageAccountName: 'azueaccvmsabc'
    backendAzureRmContainerName: 'ramk8s1'
    backendAzureRmKey: 'ram_kubernetes123'
    allowTelemetryCollection: true