trigger:
- Master

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: job1
    steps:
    - bash: echo '$(Build.BuildNumber)'
    - bash: echo '$(Build.BuildId)'
    - bash: echo '$(Build.SourceBranchName)'
    - bash: ls -R $(Build.SourceDirectory)
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '''$(Build.SourceDirectory)'''
        Contents: |
          **/*.yml
          **/*.tf
        TargetFolder: '''$(Build.ArtifactStagingDirectory)'''
    - bash: ls -R $(Build.ArtifactStagingDirectory)

  